/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import control.Controlador;
import javax.swing.DefaultComboBoxModel;
import objetos.Arma;
import objetos.Player;

/**
 *
 * @author RedCa
 */
public class Enemigo extends javax.swing.JFrame {

    /**
     * Creates new form Enemigo
     */
     public Enemigo() {
        initComponents();
    }
    
    public Enemigo(Controlador c) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.playSet = c;
        jListDialogoB.setModel(playSet.getmDialogo());
        
        jTextFieldNombreB.setText(playSet.getEnemy().getNombre());
        jProgressBarVidaB.setValue(playSet.getEnemy().getVida());
        jProgressBarEstaminaB.setValue(playSet.getEnemy().getEstamina());
        mArma = new DefaultComboBoxModel();
        for(Arma s: playSet.getEnemy().getvEquipo()){
            mArma.addElement(s.getNombre());
        }
        jComboBoxObjetoB.setModel(mArma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListDialogoB = new javax.swing.JList<>();
        jTextFieldNombreB = new javax.swing.JTextField();
        jProgressBarVidaB = new javax.swing.JProgressBar();
        jProgressBarEstaminaB = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMinimoB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEsfuerzoB = new javax.swing.JTextField();
        jComboBoxAccionB = new javax.swing.JComboBox<>();
        jComboBoxObjetoB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelNumTurno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListDialogoB);

        jTextFieldNombreB.setEditable(false);

        jProgressBarVidaB.setBackground(new java.awt.Color(204, 0, 0));
        jProgressBarVidaB.setForeground(new java.awt.Color(204, 0, 0));
        jProgressBarVidaB.setValue(100);
        jProgressBarVidaB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jProgressBarEstaminaB.setBackground(new java.awt.Color(204, 0, 0));
        jProgressBarEstaminaB.setForeground(new java.awt.Color(204, 0, 0));
        jProgressBarEstaminaB.setValue(100);
        jProgressBarEstaminaB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText(": NOMBRE");

        jLabel2.setText(": VIDA");

        jLabel3.setText(": ESTAMINA");

        jLabel4.setText(": RENDIMIENTO");

        jTextFieldMinimoB.setEditable(false);
        jTextFieldMinimoB.setText("0");

        jLabel5.setText("+");

        jTextFieldEsfuerzoB.setText("0");
        jTextFieldEsfuerzoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEsfuerzoBFocusLost(evt);
            }
        });

        jComboBoxAccionB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CURARSE", "BLOQUEAR", "FINTAR", "RETROCEDER", "ARREMETER", "ATACAR" }));
        jComboBoxAccionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAccionBActionPerformed(evt);
            }
        });

        jComboBoxObjetoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxObjetoBActionPerformed(evt);
            }
        });

        jLabel6.setText("ACCION");

        jLabel7.setText("OBJETO");

        jButton1.setText("<--- CONTINUAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setText(": TURNO");

        jLabelNumTurno.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelNumTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombreB)
                                            .addComponent(jProgressBarVidaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jProgressBarEstaminaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxObjetoB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxAccionB, 0, 145, Short.MAX_VALUE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEsfuerzoB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldMinimoB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(127, 127, 127))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreB)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarVidaB, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBarEstaminaB, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMinimoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEsfuerzoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAccionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxObjetoB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelNumTurno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String turno;
        
        playSet.getEnemy().setAccion(jComboBoxAccionB.getSelectedItem().toString());
        playSet.getEnemy().setArma(jComboBoxObjetoB.getSelectedItem().toString());
        playSet.getEnemy().setEstamina(jProgressBarEstaminaB.getValue());
        playSet.getEnemy().setEsfuerzo(Integer.parseInt(jTextFieldEsfuerzoB.getText()));
        playSet.getEnemy().setMinimo(Integer.parseInt(jTextFieldMinimoB.getText()));
        playSet.getEnemy().setVida(jProgressBarVidaB.getValue());
        
        VistaLeon zone = new VistaLeon(playSet);
        zone.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBoxAccionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAccionBActionPerformed
        String opc = jComboBoxAccionB.getSelectedItem().toString();
        
        switch (opc){
            case "CURARSE":
                jTextFieldMinimoB.setText("0");
                jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(false);
                break;
            case "BLOQUEAR":
                jTextFieldMinimoB.setText("5");
                jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(false);
                break;
            case "FINTAR":
                jTextFieldMinimoB.setText("15");
                 jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(true);
                break;
            case "RETROCEDER":
                jTextFieldMinimoB.setText("10");
                jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(false);
                break;
            case "ARREMETER":
                jTextFieldMinimoB.setText("25");
                jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(true);
                break;
            case "ATACAR":
                jTextFieldMinimoB.setText("10");
                jTextFieldEsfuerzoB.setText("0");
                jTextFieldEsfuerzoB.setEditable(true);
                break;
        }
    }//GEN-LAST:event_jComboBoxAccionBActionPerformed

    private void jTextFieldEsfuerzoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEsfuerzoBFocusLost
        int esfuerzo = Integer.parseInt(jTextFieldEsfuerzoB.getText());
        int minimo = Integer.parseInt(jTextFieldMinimoB.getText());
        int stamina = jProgressBarEstaminaB.getValue()-minimo;
        
        
        if (esfuerzo%5!=0){
            while (esfuerzo%5!=0){
                esfuerzo -= 1;   
            }
        }
        jTextFieldEsfuerzoB.setText("" + esfuerzo);
        if (esfuerzo>stamina){
            jTextFieldEsfuerzoB.setText("" + stamina);
        }
    }//GEN-LAST:event_jTextFieldEsfuerzoBFocusLost

    private void jComboBoxObjetoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxObjetoBActionPerformed
        
        String arma = jComboBoxObjetoB.getSelectedItem().toString();
        int st = jProgressBarEstaminaB.getValue();
        for(Arma r: playSet.getEnemy().getvEquipo()){
            if (arma.equals(r.getNombre())){
                mAccion = objetos.Arma.getActions(r, usos, st);
            }
        }
        jComboBoxAccionB.setModel(mAccion);
        
        
    }//GEN-LAST:event_jComboBoxObjetoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enemigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enemigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enemigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enemigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Enemigo().setVisible(true);
            }
        });
    }

    private int usos = 3;
    private DefaultComboBoxModel mAccion;
    private DefaultComboBoxModel mArma;
    private Controlador playSet;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxAccionB;
    private javax.swing.JComboBox<String> jComboBoxObjetoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNumTurno;
    private javax.swing.JList<String> jListDialogoB;
    private javax.swing.JProgressBar jProgressBarEstaminaB;
    private javax.swing.JProgressBar jProgressBarVidaB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEsfuerzoB;
    private javax.swing.JTextField jTextFieldMinimoB;
    private javax.swing.JTextField jTextFieldNombreB;
    // End of variables declaration//GEN-END:variables
}
