/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import control.Controlador;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import objetos.Arma;
import objetos.Player;

/**
 *
 * @author RedCa
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ally = new Player("", "CURARSE", null, 100, 100, 0, 0, null);
        enemy = new Player("", "CURARSE", null, 100, 100, 0, 0, null);

        vArmas = new ArrayList();
        vArmas.add(new Arma("Escudo", true, true, false, false, false, true, false, true, false, true, 150, false));
        vArmas.add(new Arma("Espada", false, true, false, false, false, true, false, false, false, false, 100, false));
        vArmas.add(new Arma("Daga", false, false, true, false, false, true, true, true, true, false, 100, false));
        vArmas.add(new Arma("Arco", false, false, true, true, false, false, true, true, false, false, 100, false));
        vArmas.add(new Arma("Hacha", false, true, false, false, true, false, false, false, false, false, 100, false));
        vArmas.add(new Arma("Lanza", false, true, false, true, false, false, true, false, false, false, 100, false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextFieldPlayer1 = new javax.swing.JTextField();
        jTextFieldPlayer2 = new javax.swing.JTextField();
        jComboBoxArma2 = new javax.swing.JComboBox<>();
        jComboBoxArma1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProp2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProp1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSec1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSec2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 58)); // NOI18N
        jButton1.setText("START");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextFieldPlayer1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jTextFieldPlayer1.setText("Player 1");
        jTextFieldPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPlayer1MouseClicked(evt);
            }
        });

        jTextFieldPlayer2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jTextFieldPlayer2.setText("Player 2");
        jTextFieldPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPlayer2MouseClicked(evt);
            }
        });

        jComboBoxArma2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jComboBoxArma2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige tu arma:", "Espada", "Lanza", "Hacha", "Daga", "Arco" }));
        jComboBoxArma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArma2ActionPerformed(evt);
            }
        });

        jComboBoxArma1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jComboBoxArma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige tu arma:", "Espada", "Lanza", "Hacha", "Daga", "Arco" }));
        jComboBoxArma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArma1ActionPerformed(evt);
            }
        });

        jTextAreaProp2.setColumns(20);
        jTextAreaProp2.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProp2);

        jTextAreaProp1.setColumns(20);
        jTextAreaProp1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProp1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Secundaria:", "Escudo", "Espada", "Lanza", "Hacha", "Daga", "Arco" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Secundaria:", "Escudo", "Espada", "Lanza", "Hacha", "Daga", "Arco" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextAreaSec1.setColumns(20);
        jTextAreaSec1.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSec1);

        jTextAreaSec2.setColumns(20);
        jTextAreaSec2.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSec2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPlayer1)
                            .addComponent(jComboBoxArma1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPlayer2)
                            .addComponent(jComboBoxArma2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPlayer1)
                    .addComponent(jTextFieldPlayer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxArma2)
                    .addComponent(jComboBoxArma1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        String player1 = jTextFieldPlayer1.getText();
        String player2 = jTextFieldPlayer2.getText();
        String principalA = jComboBoxArma1.getSelectedItem().toString();
        String principalB = jComboBoxArma2.getSelectedItem().toString();
        String secundariaA = jComboBox1.getSelectedItem().toString();
        String secundariaB = jComboBox2.getSelectedItem().toString();
        allyEquip = new ArrayList();

        enemyEquip = new ArrayList();

        for(Arma r: vArmas){
            if (principalA.equals(r.getNombre())){
                allyEquip.add(r);
            }
            if (principalB.equals(r.getNombre())){
                enemyEquip.add(r);
            }
            if (secundariaA.equals(r.getNombre())){
                allyEquip.add(r);
            }
            if (secundariaB.equals(r.getNombre())){
                enemyEquip.add(r);
            }
            
        }
        ally.setvEquipo(allyEquip);
        enemy.setvEquipo(enemyEquip);
        
        DefaultListModel mDialogo = new DefaultListModel<String>();
        ally.setNombre(player1);
        enemy.setNombre(player2);
        this.playSet = new Controlador(ally, enemy, 1, mDialogo);
        
        Aliado lobo = new Aliado(playSet);
        lobo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextFieldPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayer1MouseClicked
        
        jTextFieldPlayer1.setText("");
    }//GEN-LAST:event_jTextFieldPlayer1MouseClicked

    private void jTextFieldPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayer2MouseClicked
        jTextFieldPlayer2.setText("");
    }//GEN-LAST:event_jTextFieldPlayer2MouseClicked

    private void jComboBoxArma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArma1ActionPerformed
        
        String arma = jComboBoxArma1.getSelectedItem().toString();
        for(Arma f: vArmas){
            if(f.getNombre().equals(arma)){
                jTextAreaProp1.setText(f.toString());
            }
        } 
    }//GEN-LAST:event_jComboBoxArma1ActionPerformed

    private void jComboBoxArma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArma2ActionPerformed
        
        String arma = jComboBoxArma2.getSelectedItem().toString();
        for(Arma f: vArmas){
            if(f.getNombre().equals(arma)){
                jTextAreaProp2.setText(f.toString());
            }
        }
 
    }//GEN-LAST:event_jComboBoxArma2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String arma = jComboBox1.getSelectedItem().toString();
        for(Arma f: vArmas){
            if(f.getNombre().equals(arma)){
                jTextAreaSec1.setText(f.toString());
            }
        } 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String arma = jComboBox2.getSelectedItem().toString();
        for(Arma f: vArmas){
            if(f.getNombre().equals(arma)){
                jTextAreaSec2.setText(f.toString());
            }
        } 
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private Player ally;
    private Player enemy;
    private ArrayList<Arma> allyEquip;
    private ArrayList<Arma> enemyEquip;
    private ArrayList<Arma> vArmas;
    private Controlador playSet;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxArma1;
    private javax.swing.JComboBox<String> jComboBoxArma2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaProp1;
    private javax.swing.JTextArea jTextAreaProp2;
    private javax.swing.JTextArea jTextAreaSec1;
    private javax.swing.JTextArea jTextAreaSec2;
    private javax.swing.JTextField jTextFieldPlayer1;
    private javax.swing.JTextField jTextFieldPlayer2;
    // End of variables declaration//GEN-END:variables
}
